let dialogReturnFocus=null;
let profileWriterLease=false,profileWriterLeaseRelease=null,profileWriterLeaseRequesting=false,profileWriterLeaseGeneration=0;
const defaultMenuStatus=$("menuStatus").textContent;
function updateWriterLeaseUi(message=""){for(const id of["startBtn","resumeBtn","restartBtn","againBtn","continueCoffinBtn","skipCoffinBtn","coffinRiseBtn","coffinLeaveBtn"]){const element=$(id);if(element)element.disabled=!profileWriterLease}document.querySelectorAll('[id^="campaignNight"][id$="Btn"]').forEach(button=>{button.disabled=!profileWriterLease||button.closest(".night-card")?.classList.contains("locked")});if(message){$("menuStatus").textContent=message;$("menuStatus").classList.add("error")}else if(!profileSaveError){$("menuStatus").textContent=defaultMenuStatus;$("menuStatus").classList.remove("error")}renderMenuProfile()}
function syncProfileUi(){$("audioSetting").checked=profile.settings.audio;$("shakeSetting").checked=profile.settings.shake;$("particlesSetting").checked=profile.settings.particles;$("contrastSetting").checked=profile.settings.contrast;$("motionSetting").checked=profile.settings.reducedMotion;applySettings({persist:false});renderMenuProfile();renderScores()}
function loadWritableProfile(){try{profile=profileRepository.load();syncProfileUi();const diagnostics=profileRepository.diagnostics();if(diagnostics.source.endsWith("-volatile")){profileWriterLease=false;reportProfileSaveError(new Error(diagnostics.recoverableError));return false}return true}catch(error){profileWriterLease=false;reportProfileSaveError(error);return false}}
function setupProfileWriterLease(){if(profileWriterLeaseRequesting)return;const generation=++profileWriterLeaseGeneration;if(typeof navigator.locks?.request!=="function"){profileWriterLease=true;if(!loadWritableProfile()){updateWriterLeaseUi();return}updateWriterLeaseUi("This browser cannot coordinate game tabs. Keep only one Vampire Survival tab open.");return}profileWriterLease=false;profileWriterLeaseRequesting=true;updateWriterLeaseUi("Checking whether another Vampire Survival tab is active…");navigator.locks.request("vampire-survival-profile-writer",{ifAvailable:true},lock=>{if(generation!==profileWriterLeaseGeneration)return;if(!lock){updateWriterLeaseUi("Another Vampire Survival tab owns progress. Close it, then reload this tab to play safely.");return}profileWriterLease=true;if(!loadWritableProfile()){updateWriterLeaseUi();return}updateWriterLeaseUi();return new Promise(resolve=>{profileWriterLeaseRelease=()=>{if(generation===profileWriterLeaseGeneration)profileWriterLease=false;resolve()}})}).catch(error=>{if(generation!==profileWriterLeaseGeneration)return;profileWriterLease=false;console.warn("Cross-tab writer lock could not be acquired; play is disabled for this tab.",error);updateWriterLeaseUi("Cross-tab protection failed. Reload this tab before playing.")}).finally(()=>{if(generation===profileWriterLeaseGeneration)profileWriterLeaseRequesting=false})}
addEventListener("pagehide",()=>{if(state?.running&&!state.paused&&!state.over)togglePause(true);keys={};mouse.down=false;touch.active=false;profileWriterLeaseGeneration+=1;profileWriterLease=false;profileWriterLeaseRequesting=false;updateWriterLeaseUi("Restoring safe access to progress…");const release=profileWriterLeaseRelease;profileWriterLeaseRelease=null;if(release)release()});
addEventListener("pageshow",event=>{if(event.persisted)setupProfileWriterLease()});
function dialogFocusables(dialog){return[...dialog.querySelectorAll('button:not([disabled]),select:not([disabled]),input:not([disabled]),[href],[tabindex]:not([tabindex="-1"])')].filter(element=>!element.closest(".hidden"))}
function showDialog(id,preferredSelector){const dialog=$(id);dialogReturnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;dialog.classList.remove("hidden");requestAnimationFrame(()=>{const preferred=preferredSelector?dialog.querySelector(preferredSelector):null;(preferred||dialogFocusables(dialog)[0]||dialog).focus()})}
function hideDialog(id,restore=true){const dialog=$(id);dialog.classList.add("hidden");if(restore&&dialogReturnFocus&&document.contains(dialogReturnFocus))dialogReturnFocus.focus();dialogReturnFocus=null}
function activeDialog(){return document.querySelector('.overlay[role="dialog"]:not(.hidden)')}
function trapDialogFocus(event){if(event.code!=="Tab")return false;const dialog=activeDialog();if(!dialog)return false;const focusable=dialogFocusables(dialog);if(!focusable.length){event.preventDefault();dialog.focus();return true}const first=focusable[0],last=focusable[focusable.length-1];if(!dialog.contains(document.activeElement)){event.preventDefault();first.focus()}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}return true}
addEventListener("keydown",event=>{if(trapDialogFocus(event))return;const interactive=event.target instanceof Element&&Boolean(event.target.closest('button,select,input,textarea,a[href],[contenteditable="true"]'));if(event.code==="Escape"&&state?.running){event.preventDefault();togglePause();return}if(!profileWriterLease)return;if(BUILD.upgrades&&!$("pactModal").classList.contains("hidden")&&/^Digit[123]$/.test(event.code)){event.preventDefault();choosePact(Number(event.code.slice(-1))-1);return}if(interactive)return;if(!state?.running||state.paused||state.over)return;keys[event.code]=true;if(event.code==="Space"){event.preventDefault();triggerDash()}if(event.code==="KeyF")triggerMist();if(event.code==="KeyE")triggerSwarm()});addEventListener("keyup",event=>{keys[event.code]=false});
canvas.addEventListener("pointermove",event=>{mouse.x=event.clientX;mouse.y=event.clientY});canvas.addEventListener("pointerdown",event=>{mouse.down=true;canvas.setPointerCapture(event.pointerId);feedOrStrike()});canvas.addEventListener("pointerup",event=>{mouse.down=false;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId)});canvas.addEventListener("contextmenu",event=>event.preventDefault());
$("startBtn").addEventListener("click",()=>{if(!profileWriterLease)return;if($("gameMode").value==="campaign")openCampaignMap();else if(profile.hunt.unlocked&&profile.campaign.clears["night-5"])startRun({mode:"hunt",huntDepth:1})});
$("gameMode").addEventListener("change",renderMenuProfile);
$("campaignMapClose").addEventListener("click",returnToTitle);
$("continueCoffinBtn").addEventListener("click",continueCoffinOutcome);
$("skipCoffinBtn").addEventListener("click",finishCoffinTransition);
$("coffinRiseBtn").addEventListener("click",coffinRise);
$("coffinLeaveBtn").addEventListener("click",coffinLeave);
$("tutorialBtn").addEventListener("click",()=>showDialog("tutorial","#tutorialClose"));$("tutorialClose").addEventListener("click",()=>hideDialog("tutorial"));
$("resumeBtn").addEventListener("click",()=>{if(profileWriterLease)togglePause(false)});
$("restartBtn").addEventListener("click",()=>{if(profileWriterLease)startRun(currentRunOptions())});
$("quitBtn").addEventListener("click",returnToTitle);
$("againBtn").addEventListener("click",()=>{if(profileWriterLease)startRun(currentRunOptions())});
$("titleBtn").addEventListener("click",returnToTitle);
["audioSetting","shakeSetting","particlesSetting","contrastSetting","motionSetting"].forEach(id=>$(id).addEventListener("change",applySettings));
syncProfileUi();
setupProfileWriterLease();
function setupTouch(){if(!BUILD.platform)return;const controls=$("touchControls"),stick=$("touchStick"),knob=$("touchKnob");controls.classList.add("enabled");const updateStick=e=>{const r=stick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),len=Math.hypot(x,y),max=r.width*.34,scale=len>max?max/len:1;touch.x=x*scale/max;touch.y=y*scale/max;knob.style.transform=`translate(${x*scale}px,${y*scale}px)`};stick.addEventListener("pointerdown",e=>{touch.active=true;stick.setPointerCapture(e.pointerId);updateStick(e)});stick.addEventListener("pointermove",e=>{if(touch.active)updateStick(e)});const stop=e=>{touch.active=false;touch.x=0;touch.y=0;knob.style.transform="translate(0,0)";if(stick.hasPointerCapture(e.pointerId))stick.releasePointerCapture(e.pointerId)};stick.addEventListener("pointerup",stop);stick.addEventListener("pointercancel",stop);controls.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();const a=b.dataset.action;if(a==="feed")feedOrStrike();else if(a==="dash")triggerDash();else if(a==="mist")triggerMist();else if(a==="swarm")triggerSwarm();else if(a==="pause")togglePause()}))}
setupTouch();
