function difficulty(){return DIFFICULTIES[state.difficulty]}
function runSeed(){return createRunSeed(BUILD.platform?$("runMode").value:"standard")}
function newRunId(){if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==="function")return"run:"+globalThis.crypto.randomUUID();return"run:"+Date.now().toString(36)+":"+Math.random().toString(36).slice(2)}
function districtAt(x,y){for(const d of DISTRICTS)if(x>=d.x&&x<d.x+d.w&&y>=d.y&&y<d.y+d.h)return d;throw new Error(`World position is outside all districts: ${x},${y}`)}
function activeDistrict(){return districtAt(player.x,player.y)}
function rectCircleCollision(rect,x,y,r){const nx=clamp(x,rect.x,rect.x+rect.w),ny=clamp(y,rect.y,rect.y+rect.h);return(x-nx)**2+(y-ny)**2<r*r}
function blocked(x,y,r=15){if(x<r||y<r||x>WORLD.w-r||y>WORLD.h-r)return true;for(const b of buildings)if(rectCircleCollision(b,x,y,r))return true;return false}
function moveEntity(entity,dx,dy,radius){const nx=entity.x+dx;if(!blocked(nx,entity.y,radius))entity.x=nx;const ny=entity.y+dy;if(!blocked(entity.x,ny,radius))entity.y=ny;entity.x=clamp(entity.x,radius,WORLD.w-radius);entity.y=clamp(entity.y,radius,WORLD.h-radius)}
function safePoint(preferredX,preferredY,radius=28){if(!blocked(preferredX,preferredY,radius))return{x:preferredX,y:preferredY};for(let ring=1;ring<28;ring++){for(let n=0;n<20;n++){const a=n/20*TAU,x=preferredX+Math.cos(a)*ring*28,y=preferredY+Math.sin(a)*ring*28;if(!blocked(x,y,radius))return{x,y}}}throw new Error("Unable to locate a safe city position")}
function makeCity(){buildings=[];lanterns=[];const road=118;for(const d of DISTRICTS){for(let gy=d.y+70;gy<d.y+d.h-80;gy+=190){for(let gx=d.x+70;gx<d.x+d.w-80;gx+=210){if(Math.abs((gx-d.x)%630)<road||Math.abs((gy-d.y)%570)<road)continue;const w=82+rng()*72,h=62+rng()*76;buildings.push({x:gx,y:gy,w,h,district:d.id,kind:rng()<.14?"tower":"house",lit:rng()<.42})}}for(let i=0;i<18;i++)lanterns.push({x:d.x+50+rng()*(d.w-100),y:d.y+50+rng()*(d.h-100),r:65+rng()*48,p:rng()*TAU,district:d.id})}invariant(buildings.length>55,"City generation produced too few buildings")}
function resetRun(){const seed=runSeed();rng=mulberry32(hashText(seed));makeCity();state={gamePhase:GAME_PHASES.MENU,runId:newRunId(),running:false,paused:false,over:false,win:false,time:0,score:0,phase:1,threat:1,difficulty:$("difficulty").value,seed,spawnTimer:0,relicsBroken:0,requiredCrosses:0,dawn:DIFFICULTIES[$("difficulty").value].dawn,grace:DIFFICULTIES[$("difficulty").value].grace,toast:"",toastTime:0,district:"",pactPending:0,hitStop:0,kills:0,damageTaken:0,roses:0,bossIntro:0,frenzy:0,bloodMoon:0,director:{pressure:1,budget:0},newAchievements:[]};player={x:WORLD.w/2,y:WORLD.h/2,radius:15,vx:0,vy:0,blood:112,maxBlood:112,xp:0,nextXp:62,level:1,speed:248,range:74,feedDamage:25,attackCd:0,dashTime:0,dashCd:0,mistTime:0,mistCd:0,mistBase:8.5,mistDuration:2.15,swarmCd:0,swarmDamage:34,swarmRadius:215,relicDamage:48,hitFlash:0,combo:0,comboTime:0,comboWindow:3.2,scoreBonus:0,magnet:28,roseHeal:18,echo:false,feedCount:0,thorns:false,frenzyGain:1,pacts:{},lastDistrict:"",facing:0};enemies=[];relics=[];particles=[];stains=[];bullets=[];pickups=[];hazards=[];telegraphs=[];floaters=[];currentPacts=[];boss=null;entityCounter=0;const spawn=safePoint(WORLD.w/2,WORLD.h/2);player.x=spawn.x;player.y=spawn.y;const relicPoints=[[420,360],[WORLD.w-440,420],[WORLD.w*.52,WORLD.h-360]];state.requiredCrosses=relicPoints.length;relicPoints.forEach((p,i)=>{const q=safePoint(p[0],p[1],42);relics.push({x:q.x,y:q.y,radius:34,hp:150+i*45,maxHp:150+i*45,active:true,pulse:rng()*TAU,ward:0})});for(let i=0;i<18;i++)spawnEnemy("villager",true);for(let i=0;i<3;i++)spawnEnemy("guard",true);updateHud()}
function enemyTypeForTime(){const p=state.phase,r=rng();if(p>=5&&r<.09)return"captain";if(p>=4&&r<.24)return"priest";if(p>=3&&r<.48)return"hunter";if(p>=2&&r<.72)return"guard";return"villager"}
function randomOpenPoint(inside=true){for(let tries=0;tries<120;tries++){let x,y;if(inside){x=60+rng()*(WORLD.w-120);y=60+rng()*(WORLD.h-120)}else{const e=Math.floor(rng()*4);x=e===1?WORLD.w-32:e===3?32:60+rng()*(WORLD.w-120);y=e===0?32:e===2?WORLD.h-32:60+rng()*(WORLD.h-120)}if(!blocked(x,y,28)&&Math.hypot(x-player.x,y-player.y)>250)return{x,y}}throw new Error("Unable to spawn enemy in generated city")}
function spawnEnemy(type=enemyTypeForTime(),inside=false,elite=false){const base=ENEMY_TYPES[type],p=randomOpenPoint(inside),d=difficulty(),district=districtAt(p.x,p.y);elite=elite||(BUILD.upgrades&&type!=="villager"&&rng()<.035+state.phase*.012+(BUILD.districts&&district.id==="palace"?.06:0));const hp=base.hp*d.enemyHp*(elite?1.75:1);const e={id:"enemy-"+(++entityCounter),type,behaviour:base.behaviour,x:p.x,y:p.y,radius:base.radius+(elite?2:0),hp,maxHp:hp,speed:base.speed*(elite?1.12:1),damage:base.damage*d.enemyDamage*(elite?1.35:1),score:base.score*(elite?2.1:1),xp:base.xp*(elite?1.7:1),state:base.behaviour==="flee"?"roam":"patrol",target:randomOpenPoint(true),cooldown:rng()*1.4,shotCd:.4+rng(),hit:0,angle:rng()*TAU,elite,shield:type!=="villager"&&rng()<.38,torch:rng()<.24,dead:false};enemies.push(e);return e}
function spawnBoss(){if(boss!==null)return boss;const p=safePoint(WORLD.w*.5,220,45),base=ENEMY_TYPES.voss,d=difficulty();boss={id:"captain-voss",type:"voss",behaviour:base.behaviour,x:p.x,y:p.y,radius:base.radius,hp:base.hp*d.enemyHp,maxHp:base.hp*d.enemyHp,speed:base.speed,damage:base.damage*d.enemyDamage,score:base.score,xp:base.xp,state:"boss",cooldown:1.6,shotCd:1.1,hit:0,angle:0,phase:1,pattern:"arrival",patternTime:1.4,elite:true,dead:false,target:{x:player.x,y:player.y}};enemies.push(boss);state.bossIntro=BUILD.polish?1.35:0;$("bossWrap").style.display="block";toast("Captain Voss enters the hunt",3);chord(72,61,49);return boss}
